/**
 * \file Ring.cpp
 *
 * \author Craig Smith
 *
 * Class that implements the Ring generated by TowerRing
 */

#include "pch.h"
#include "Ring.h"
#include "TowerRing.h"

using namespace Gdiplus;

CRing::CRing(CGame* game) : CItem(game)
{
	mXInit = mX;
	mYInit = mY;
}

void CRing::Update(double elapsed)
{
	if (mActive)
	{
		if (mDiameter < mDiameterMax)
		{
			mDiameter += elapsed * mFireRate;
			mX -= elapsed * mFireRate/2.35;
			mY -= elapsed * mFireRate/2.35;
		}
		else {
			mDiameter = mDiameterInitial;
			mX = mXInit;
			mY = mYInit;
			mActive = false;
		}
	}
}

void CRing::Draw(Gdiplus::Graphics* graphics)
{
	Pen pen(Color(255, 0, 0), 2);
	graphics->DrawEllipse(&pen, mX, mY, mDiameter, mDiameter);
}
