/**
 * \file Ring.h
 *
 * \author Craig Smith
 *
 * Class that implements the Ring generated by TowerRing
 */

#pragma once
#include "Item.h"
#include "Game.h"
#include "ItemVisitor.h"


 /**
 * CRing class
 */
class CRing :
    public CItem
{

public:
	CRing() = delete;

	/**
	 * Copy constructor (disabled)
	 */
	CRing(const CRing&) = delete;

	/**
	 * CRing constructor
	 * \param game Pointer to the game which we belong
	 */
	CRing(CGame* game);

	/// Fire the ring
	void Fire() { mActive = true; };

	/// Handle updates for animation
	/// \param elapsed The time since the last update
	virtual void Update(double elapsed);

	/// Draw the image
	/// \param graphics Graphics context
	virtual void Draw(Gdiplus::Graphics* graphics);

	/** Accept a visitor
	 * \param visitor The visitor we accept */
	virtual void Accept(CItemVisitor* visitor) {};

	/**
	 * Setter for X position
	 * \param xPos desired X position
	 */
	virtual void SetX(double xPos) override { CItem::SetX(xPos); mXInit = xPos; }

	/**
	 * Setter for Y position
	 * \param yPos desired Y position
	 */
	virtual void SetY(double yPos) override { CItem::SetY(yPos); mYInit = yPos; }

	/**
	* Setter for Y and X positions
	* \param yPos desired Y position
	* \param xPos desired X position
	*/
	virtual void SetCoordinates(double yPos, double xPos) override { CItem::SetX(xPos); CItem::SetY(yPos); mXInit = xPos; mYInit = yPos; }

	/**
	* Get current diameter of ring
	* \return diameter of ring
	*/
	int GetRingDiameter() { return mDiameter; };

	/**
	* Is ring active
	* \return if active
	*/
	bool IsActive() { return mActive; };

private:
	/// Current diameter of the ring
	int mDiameter = 20;

	/// Initial diameter of the ring (equal to radius * 2)
	double mDiameterInitial = 20;

	/// Maximum diameter of the ring when fired (equal to radius * 2)
	double mDiameterMax = 200;

	/// Rate of fire, in pixels per second
	double mFireRate = 200;

	/// If ring is currently being fired
	bool mActive = false;

	/// Initial X position of the ring, will be set back to this location after firing
	int mXInit = 0;

	/// Initial Y position of the ring, will be set back to this location after firing
	int mYInit = 0;
};

